-- Generated by cpld_vhdl_generator; regenerate instead of editing.
-- Selected contract: $contract; request: $request_mode; carrier ready: $carrier_ready.
library ieee;
use ieee.std_logic_1164.all;

entity s3c_logic is
    port (
        clk, reset : in std_logic;
        reqsafestate, carrierrdy, pilot_in, card_enable : in std_logic;
        state_normal, state_safe : out std_logic;
        slotok, reqoe : out std_logic
    );
end entity;

architecture rtl of s3c_logic is
    type state_type is (safe_state, normal_state);
    signal state : state_type := safe_state;
$declarations
    signal warmup : natural range 0 to 3 := 0;
    signal request_safe, permit_normal, pilot_ok : std_logic;
begin
    -- Normalize only the selected contract; unknown control levels request safe_state.
    permit_normal <= '1' when reset = '0' and warmup = 3$ready else '0';
    request_safe <= '0' when permit_normal = '1' and request_sync = '${normal_level}' else '1';
    pilot_ok <= $pilot_ok;
    process(clk)
    begin
        if rising_edge(clk) then
            if reset = '1' then
                state <= safe_state;
$reset_lines
                warmup <= 0;
            else
$sampling
                if warmup < 3 then
                    warmup <= warmup + 1;
                    state <= safe_state;
                else
                    case state is
                        when safe_state =>
                            if request_safe = '0' and enable_sync = '1' and pilot_ok = '1' then
                                state <= normal_state;
                            end if;
                        when normal_state =>
                            if request_safe /= '0' or enable_sync /= '1' or pilot_ok /= '1' then
                                state <= safe_state;
                            end if;
                    end case;
                end if;
            end if;
        end if;
    end process;
    state_normal <= '1' when state = normal_state and reset = '0' else '0';
    state_safe <= '1' when state = safe_state or reset /= '0' else '0';
$status
end architecture;
