-- Generated by cpld_vhdl_generator; regenerate instead of editing.
-- Selected contract: $contract; request: $request_mode; carrier ready: $carrier_ready.
library ieee;
use ieee.std_logic_1164.all;

entity s3c_logic is
    port (
        clk, reset : in std_logic;
        reqsafestate, carrierrdy, pilot_in, card_enable : in std_logic;
        state_normal, state_safe, state_error : out std_logic;
        slotok, reqoe : out std_logic
    );
end entity;

architecture rtl of s3c_logic is
    type state_type is (SAFE, NORMAL, ERROR);
    signal state : state_type := SAFE;
$declarations
    signal warmup : natural range 0 to 3 := 0;
    signal safe_seen : std_logic := '0';
    signal request_safe, permit_normal, fault_present : std_logic;
begin
    -- Normalize only the selected contract; unknown control levels request SAFE.
    permit_normal <= '1' when reset = '0' and warmup = 3 and $ready else '0';
    request_safe <= '0' when permit_normal = '1' and request_sync = '${normal_level}' else '1';
    fault_present <= $fault;
    process(clk)
    begin
        if rising_edge(clk) then
            if reset = '1' then
                state <= SAFE;
$reset_lines
                warmup <= 0;
                safe_seen <= '0';
            else
$sampling
                if warmup < 3 then
                    warmup <= warmup + 1;
                    state <= SAFE;
                else
                    case state is
                        when ERROR =>
                            if request_safe = '1' then
                                safe_seen <= '1';
                            else
                                safe_seen <= '0';
                            end if;
                            -- A release while the fault persists consumes the safe cycle.
                            if fault_present = '0' and safe_seen = '1' and request_safe = '0' then
                                state <= SAFE;
                                safe_seen <= '0';
                            end if;
                        when SAFE =>
                            if fault_present = '1' then
                                state <= ERROR;
                                safe_seen <= '0';
                            elsif request_safe = '0' and enable_sync = '1' then
                                state <= NORMAL;
                            end if;
                        when NORMAL =>
                            if fault_present = '1' then
                                state <= ERROR;
                                safe_seen <= '0';
                            elsif request_safe /= '0' or enable_sync /= '1' then
                                state <= SAFE;
                            end if;
                    end case;
                end if;
            end if;
        end if;
    end process;
    state_normal <= '1' when state = NORMAL and reset = '0' else '0';
    state_error <= '1' when state = ERROR and reset = '0' else '0';
    state_safe <= '1' when state = SAFE or reset /= '0' else '0';
$status
end architecture;
