[options]
packages = find:
include_package_data = True

[options.packages.find]
include =
    cpld_toolchain*
    xo2_library*
exclude =
    cpld_toolchain.cpld_vhdl_generator.tests*
    cpld_toolchain.toolchain.tests*
    cpld_toolchain.programmer_helper.tests*
    cpld_toolchain.tests*
    xo2_library.tests*

[options.package_data]
cpld_toolchain = uv-bootstrap.json
cpld_toolchain.cpld_vhdl_generator = contracts/*.toml, targets/*.lpf
cpld_toolchain.toolchain = targets/*/*, hdl/*, foss/*.json, foss/*.patch, foss/tests/*.cpp, analysis/*.txt, simulation/*.txt, venv-shell.bash
cpld_toolchain.programmer_helper = *.sh, *.toml
xo2_library = s3c/*.vhdl
