-- Generated by cpld_vhdl_generator; regenerate instead of editing.
library ieee;
use ieee.std_logic_1164.all;

library s3c;

entity cvg_voltage_8rx_8tx_8tx_6tx is
    port (
        pilot_in : in std_logic;
        reqsafestate : in std_logic;
        carrierrdy : in std_logic;
        slotok : out std_logic;
        reqoe : out std_logic;
        i2c_scl : in std_logic;
        i2c_sda : in std_logic;
        fpga_00 : out std_logic;
        fpga_01 : out std_logic;
        fpga_02 : out std_logic;
        fpga_03 : out std_logic;
        fpga_04 : out std_logic;
        fpga_05 : out std_logic;
        fpga_06 : out std_logic;
        fpga_07 : out std_logic;
        fpga_08 : in std_logic;
        fpga_09 : in std_logic;
        fpga_10 : in std_logic;
        fpga_11 : in std_logic;
        fpga_12 : in std_logic;
        fpga_13 : in std_logic;
        fpga_14 : in std_logic;
        fpga_15 : in std_logic;
        fpga_16 : in std_logic;
        fpga_17 : in std_logic;
        fpga_18 : in std_logic;
        fpga_19 : in std_logic;
        fpga_20 : in std_logic;
        fpga_21 : in std_logic;
        fpga_22 : in std_logic;
        fpga_23 : in std_logic;
        fpga_24 : in std_logic;
        fpga_25 : in std_logic;
        fpga_26 : in std_logic;
        fpga_27 : in std_logic;
        fpga_28 : in std_logic;
        fpga_29 : in std_logic;
        d_00 : in std_logic;
        d_01 : in std_logic;
        d_02 : in std_logic;
        d_03 : in std_logic;
        d_04 : in std_logic;
        d_05 : in std_logic;
        d_06 : in std_logic;
        d_07 : in std_logic;
        d_08 : out std_logic;
        d_09 : out std_logic;
        d_10 : out std_logic;
        d_11 : out std_logic;
        d_12 : out std_logic;
        d_13 : out std_logic;
        d_14 : out std_logic;
        d_15 : out std_logic;
        d_16 : out std_logic;
        d_17 : out std_logic;
        d_18 : out std_logic;
        d_19 : out std_logic;
        d_20 : out std_logic;
        d_21 : out std_logic;
        d_22 : out std_logic;
        d_23 : out std_logic;
        d_24 : out std_logic;
        d_25 : out std_logic;
        d_26 : out std_logic;
        d_27 : out std_logic;
        d_28 : out std_logic;
        d_29 : out std_logic
    );
end entity;

architecture rtl of cvg_voltage_8rx_8tx_8tx_6tx is
    signal s3c_normal_state, s3c_card_enable : std_logic;
    signal s3c_system_error : std_logic;
    signal s3c_clk : std_logic;
    component OSCH
        generic (NOM_FREQ : string := "2.08");
        port (STDBY : in std_logic; OSC, SEDSTDBY : out std_logic);
    end component;
begin
    oscillator: OSCH generic map (NOM_FREQ => "2.08")
        port map (STDBY => '0', OSC => s3c_clk, SEDSTDBY => open);
    s3c_card_enable <= '1';
    controller: entity s3c.s3c_logic(heartbeat)
        generic map (
            REQUIRE_PILOT => false,
            REQUEST_SAFE_LEVEL => '1',
            USE_CARRIER_READY => true,
            CARRIER_READY_LEVEL => '1',
            HB_MAX_EDGE_CLKS => 52,
            HB_MIN_EDGE_CLKS => 10,
            HB_TIMEOUT_CLKS => 208,
            HB_VALID_EDGES_REQUIRED => 16,
            SLOTOK_NORMAL => '1',
            SLOTOK_SAFE => '0',
            REQOE_NORMAL => '1',
            REQOE_SAFE => '1'
        )
        port map (
            clk => s3c_clk,
            reset => '0',
            pilot_in => pilot_in,
            reqsafestate => reqsafestate,
            carrierrdy => carrierrdy,
            slotok => slotok,
            reqoe => reqoe,
            card_enable => s3c_card_enable,
            state_normal => s3c_normal_state,
            state_safe => open,
            state_system_error => s3c_system_error
        );
    fpga_00 <= '0' when s3c_system_error = '1' else d_00 when s3c_normal_state = '1' else d_00;
    fpga_01 <= '0' when s3c_system_error = '1' else d_01 when s3c_normal_state = '1' else d_01;
    fpga_02 <= '0' when s3c_system_error = '1' else d_02 when s3c_normal_state = '1' else d_02;
    fpga_03 <= '0' when s3c_system_error = '1' else d_03 when s3c_normal_state = '1' else d_03;
    fpga_04 <= '0' when s3c_system_error = '1' else d_04 when s3c_normal_state = '1' else d_04;
    fpga_05 <= '0' when s3c_system_error = '1' else d_05 when s3c_normal_state = '1' else d_05;
    fpga_06 <= '0' when s3c_system_error = '1' else d_06 when s3c_normal_state = '1' else d_06;
    fpga_07 <= '0' when s3c_system_error = '1' else d_07 when s3c_normal_state = '1' else d_07;
    d_08 <= '0' when s3c_system_error = '1' else fpga_08 when s3c_normal_state = '1' else '0';
    d_09 <= '0' when s3c_system_error = '1' else fpga_09 when s3c_normal_state = '1' else '0';
    d_10 <= '0' when s3c_system_error = '1' else fpga_10 when s3c_normal_state = '1' else '0';
    d_11 <= '0' when s3c_system_error = '1' else fpga_11 when s3c_normal_state = '1' else '0';
    d_12 <= '0' when s3c_system_error = '1' else fpga_12 when s3c_normal_state = '1' else '0';
    d_13 <= '0' when s3c_system_error = '1' else fpga_13 when s3c_normal_state = '1' else '0';
    d_14 <= '0' when s3c_system_error = '1' else fpga_14 when s3c_normal_state = '1' else '0';
    d_15 <= '0' when s3c_system_error = '1' else fpga_15 when s3c_normal_state = '1' else '0';
    d_16 <= '0' when s3c_system_error = '1' else fpga_16 when s3c_normal_state = '1' else '0';
    d_17 <= '0' when s3c_system_error = '1' else fpga_17 when s3c_normal_state = '1' else '0';
    d_18 <= '0' when s3c_system_error = '1' else fpga_18 when s3c_normal_state = '1' else '0';
    d_19 <= '0' when s3c_system_error = '1' else fpga_19 when s3c_normal_state = '1' else '0';
    d_20 <= '0' when s3c_system_error = '1' else fpga_20 when s3c_normal_state = '1' else '0';
    d_21 <= '0' when s3c_system_error = '1' else fpga_21 when s3c_normal_state = '1' else '0';
    d_22 <= '0' when s3c_system_error = '1' else fpga_22 when s3c_normal_state = '1' else '0';
    d_23 <= '0' when s3c_system_error = '1' else fpga_23 when s3c_normal_state = '1' else '0';
    d_24 <= '0' when s3c_system_error = '1' else fpga_24 when s3c_normal_state = '1' else '0';
    d_25 <= '0' when s3c_system_error = '1' else fpga_25 when s3c_normal_state = '1' else '0';
    d_26 <= '0' when s3c_system_error = '1' else fpga_26 when s3c_normal_state = '1' else '0';
    d_27 <= '0' when s3c_system_error = '1' else fpga_27 when s3c_normal_state = '1' else '0';
    d_28 <= '0' when s3c_system_error = '1' else fpga_28 when s3c_normal_state = '1' else '0';
    d_29 <= '0' when s3c_system_error = '1' else fpga_29 when s3c_normal_state = '1' else '0';
end architecture;
