name = "tx16_14rx"
top = "SignalRouter"
standard = "1993"
synthesis = "lse"
targets = ["uz_dslot_xo2"]
constraints = ["tx16_14rx_constraints.lpf"]
sources = [{path = "tx16_14rx.vhdl", library = "work"}]
testbench = "tx16_14rx_tb.py"
