name = "tx20_10rx"
top = "SignalRouter"
standard = "2008"
synthesis = "synplify"
targets = ["uz_dslot_xo2"]
backends = ["diamond"]
constraints = ["tx20_10rx_constraints.lpf"]
sources = [
    {path = "../../../xo2_library/s3c/s3c_logic.vhdl", library = "s3c"},
    {path = "../../../xo2_library/s3c/heartbeat.vhdl", library = "s3c"},
    {path = "tx20_10rx.vhdl", library = "work"},
]
testbench = "tx20_10rx_tb.py"
