name = "uz_d_temperature_ltc2983"
top = "SignalRouter"
standard = "1993"
synthesis = "lse"
targets = ["uz_dslot_xo2"]
constraints = ["uz_d_temperature_ltc2983_constraints.lpf"]
sources = [{path = "uz_d_temperature_ltc2983.vhdl", library = "work"}]
testbench = "uz_d_temperature_ltc2983_tb.py"
