name = "uz_d_resolver_d5"
top = "SignalRouter"
standard = "1993"
targets = ["uz_dslot_xo2"]
constraints = ["uz_d_resolver_d5_constraints.lpf"]
sources = [{path = "uz_d_resolver_d5.vhdl", library = "work"}]
testbench = "uz_d_resolver_d5_tb.py"
