name = "cvg_tx30_stateful"
top = "cvg_tx30_stateful"
standard = "1993"
targets = ["uz_dslot_xo2"]
backends = ["diamond", "foss"]
constraints = ["cvg_tx30_stateful_constraints.lpf"]
generator = "generator.toml"
sources = [{path = "../../../cpld_vhdl_generator/hdl/s3c_logic.vhdl", library = "s3c"}, {path = "../../../cpld_vhdl_generator/hdl/level_signals.vhdl", library = "s3c"}, {path = "cvg_tx30_stateful.vhdl", library = "work"}]
testbench = "cvg_tx30_stateful_tb.py"
