name = "voltage_8tx_8tx_8rx_6rx"
top = "SignalRouter"
standard = "1993"
synthesis = "synplify"
targets = ["uz_dslot_xo2"]
backends = ["diamond"]
constraints = ["voltage_8tx_8tx_8rx_6rx_constraints.lpf"]
sources = [
    {path = "../../../xo2_library/s3c/s3c_logic.vhdl", library = "s3c"},
    {path = "../../../xo2_library/s3c/heartbeat.vhdl", library = "s3c"},
    {path = "voltage_8tx_8tx_8rx_6rx.vhdl", library = "work"},
]
testbench = "voltage_8tx_8tx_8rx_6rx_tb.py"
