name = "uz_d_voltage_003_5v_tx30"
top = "SignalRouter"
standard = "1993"
synthesis = "lse"
targets = ["uz_dslot_xo2"]
constraints = ["uz_d_voltage_003_5v_tx30_constraints.lpf"]
sources = [{path = "tx30.vhdl", library = "work"}]
testbench = "uz_d_voltage_003_5v_tx30_tb.py"
