"""Generate a repository manifest, board constraints and a routing testbench."""
import json
import os

from .generator import PACKAGE, source_entries


def render_project(config, output):
    """Use the fixed D-slot board pin map and the configured I/O directions."""
    name = config.name
    manifest = {
        'name': name, 'top': name, 'standard': '1993',
        'targets': [config.target], 'backends': ['diamond'],
        'constraints': [name + '_constraints.lpf'],
        'generator': os.path.relpath(config.path, output),
        'sources': [{'path': os.path.relpath(source.path, output), 'library': source.library}
                    for source in source_entries(config, output)],
        'testbench': name + '_tb.py',
    }

    def toml(value):
        if isinstance(value, dict):
            return '{' + ', '.join(f'{key} = {toml(item)}' for key, item in value.items()) + '}'
        if isinstance(value, list):
            return '[' + ', '.join(toml(item) for item in value) + ']'
        return json.dumps(value)

    contract = config.contract
    parameters = {
        'INPUTS': [pin.name for pin in config.pins if pin.direction == 'in'],
        'ROUTES': {pin.name: pin.actions for pin in config.pins if pin.direction == 'out'},
        'ENABLE': dict(sorted(config.enable.items())),
        'REQUEST_SAFE': int(contract['request_mode'] == 'active_high'),
        'READY_LEVEL': int(contract['carrier_ready'] != 'active_low'),
        'USE_READY': contract['carrier_ready'] != 'unused',
        'REQUIRE_PILOT': config.pilot_policy == 'required',
        'SLOTOK': contract['slotok'], 'REQOE': contract['reqoe'],
    }
    testbench = ('# Generated by cpld_vhdl_generator; regenerate instead of editing.\n' +
                 ''.join(f'{key} = {value!r}\n' for key, value in parameters.items()) + TESTBENCH)
    return {
        name + '.toml': '# Generated by cpld_vhdl_generator; regenerate instead of editing.\n' +
                       ''.join(f'{key} = {toml(value)}\n' for key, value in manifest.items()),
        name + '_constraints.lpf': (PACKAGE / 'targets' / (config.target + '.lpf')).read_text(),
        name + '_tb.py': testbench,
    }


TESTBENCH = '''

import cocotb
from cocotb.triggers import Timer


@cocotb.test()
async def generated_routing(dut):
    """Check data directions, both routing states, and configured controls."""
    # OSCH is unbound in RTL simulation; drive its internal clock net.
    clock = dut.cvg_clk
    clock.value = 0
    dut.reqsafestate.value = REQUEST_SAFE
    dut.carrierrdy.value = READY_LEVEL
    dut.pilot_in.value = int(REQUIRE_PILOT)
    dut.i2c_scl.value = 0
    dut.i2c_sda.value = 0
    values = {pin: ENABLE.get(pin, 0) for pin in INPUTS}
    for pin, value in values.items():
        getattr(dut, pin).value = value

    async def tick(count=3):
        for _ in range(count):
            clock.value = 0
            await Timer(5, unit='ns')
            clock.value = 1
            await Timer(5, unit='ns')

    async def check(normal):
        await Timer(1, unit='ns')
        index = 0 if normal else 1
        assert int(dut.slotok.value) == SLOTOK[index], 'slotok'
        assert int(dut.reqoe.value) == REQOE[index], 'reqoe'
        for pin, actions in ROUTES.items():
            action = actions[index]
            expected = action if action in ('0', '1', 'Z') else str(values[action])
            actual = str(getattr(dut, pin).value).upper()
            assert actual == expected, (pin, normal, action, expected, actual)

    async def patterns(normal):
        # Hold enable inputs at their required levels while exercising routing.
        for background in (0, 1):
            for pin in INPUTS:
                values[pin] = ENABLE.get(pin, background)
                getattr(dut, pin).value = values[pin]
            await check(normal)
            for pin in INPUTS:
                if pin in ENABLE:
                    continue
                values[pin] = 1 - background
                getattr(dut, pin).value = values[pin]
                await check(normal)
                values[pin] = background
                getattr(dut, pin).value = values[pin]
            await check(normal)

    await tick(12)
    await patterns(False)
    dut.reqsafestate.value = 1 - REQUEST_SAFE
    await tick()
    await patterns(True)
    dut.reqsafestate.value = REQUEST_SAFE
    await tick()
    await patterns(False)
    dut.reqsafestate.value = 1 - REQUEST_SAFE
    await tick()
    await check(True)

    dut.pilot_in.value = 0
    await tick()
    await check(not REQUIRE_PILOT)
    dut.pilot_in.value = 1
    await tick()
    await check(True)
    dut.carrierrdy.value = 1 - READY_LEVEL
    await tick()
    await check(not USE_READY)
    dut.carrierrdy.value = READY_LEVEL
    await tick()
    await check(True)
    for pin, required in ENABLE.items():
        values[pin] = 1 - required
        getattr(dut, pin).value = values[pin]
        await tick()
        await check(False)
        values[pin] = required
        getattr(dut, pin).value = required
        await tick()
        await check(True)
'''
