"""Generate a repository manifest, board constraints and a routing testbench."""
import os
from pathlib import Path

from .generator import PACKAGE, source_entries
from .toml import dumps


def render_project(config, output):
    """Use the fixed D-slot board pin map and the configured I/O directions."""
    name = config.name
    manifest = {
        'name': name, 'top': name, 'standard': config.standard, 'synthesis': config.synthesis,
        'targets': [config.target], 'backends': ['diamond'],
        'constraints': [name + '_constraints.lpf'],
        'generator': Path(os.path.relpath(config.path, output)).as_posix(),
        'sources': [{'path': Path(os.path.relpath(source.path, output)).as_posix(), 'library': source.library}
                    for source in source_entries(config, output)],
        'testbench': name + '_tb.py',
    }

    contract = config.contract
    parameters = {
        'INPUTS': [pin.name for pin in config.pins if pin.direction == 'in'],
        'ROUTES': {pin.name: pin.actions for pin in config.pins if pin.direction == 'out'},
        'ENABLE': dict(sorted(config.enable.items())),
        'REQUEST_SAFE': int(contract['request_mode'] == 'active_high'),
        'READY_LEVEL': int(contract['carrier_ready'] != 'active_low'),
        'USE_READY': contract['carrier_ready'] != 'unused',
        'HEARTBEAT': contract.get('heartbeat'),
        'REQUIRE_PILOT': config.pilot_policy == 'required',
        'SLOTOK': contract['slotok'], 'REQOE': contract['reqoe'],
    }
    testbench = ('# Generated by cpld_vhdl_generator; regenerate instead of editing.\n' +
                 ''.join(f'{key} = {value!r}\n' for key, value in parameters.items()) + TESTBENCH)
    return {
        name + '.toml': '# Generated by cpld_vhdl_generator; regenerate instead of editing.\n' +
                       dumps(manifest),
        name + '_constraints.lpf': (PACKAGE / 'targets' / (config.target + '.lpf')).read_text(encoding="utf-8"),
        name + '_tb.py': testbench,
    }


TESTBENCH = '''

import cocotb
from cocotb.triggers import Timer


@cocotb.test()
async def generated_routing(dut):
    """Check normal/safe routing and the mandatory latched system-error override."""
    # OSCH is unbound in RTL simulation; drive its internal clock net.
    clock = dut.s3c_clk
    clock.value = 0
    dut.reqsafestate.value = 1 - REQUEST_SAFE
    dut.carrierrdy.value = 0 if HEARTBEAT else READY_LEVEL
    dut.pilot_in.value = int(REQUIRE_PILOT)
    dut.i2c_scl.value = 0
    dut.i2c_sda.value = 0
    values = {pin: ENABLE.get(pin, 0) for pin in INPUTS}
    for pin, value in values.items():
        getattr(dut, pin).value = value

    hb_running = False
    hb_count, hb_level = 0, 0
    hb_period = ((HEARTBEAT['min_edge_clks'] + HEARTBEAT['max_edge_clks']) // 2
                 if HEARTBEAT else 1)
    qualify_cycles = (HEARTBEAT['valid_edges_required'] + 1) * hb_period + 3 if HEARTBEAT else 4

    async def tick(count=3):
        nonlocal hb_count, hb_level
        for _ in range(count):
            clock.value = 0
            if HEARTBEAT and hb_running:
                hb_count += 1
                if hb_count >= hb_period:
                    hb_count = 0
                    hb_level = 1 - hb_level
                    dut.carrierrdy.value = hb_level
            await Timer(5, unit='ns')
            clock.value = 1
            await Timer(5, unit='ns')

    async def check(normal, system_error=False):
        await Timer(1, unit='ns')
        index = 0 if normal else 1
        assert int(dut.slotok.value) == (0 if system_error else SLOTOK[index]), 'slotok'
        assert int(dut.reqoe.value) == (0 if system_error else REQOE[index]), 'reqoe'
        assert int(dut.s3c_system_error.value) == int(system_error), 'system_error'
        for pin, actions in ROUTES.items():
            action = actions[index]
            expected = '0' if system_error else (action if action in ('0', '1', 'Z') else str(values[action]))
            actual = str(getattr(dut, pin).value).upper()
            assert actual == expected, (pin, normal, action, expected, actual)

    async def patterns(normal, system_error=False):
        # Hold enable inputs at their required levels while exercising routing.
        for background in (0, 1):
            for pin in INPUTS:
                values[pin] = ENABLE.get(pin, background)
                getattr(dut, pin).value = values[pin]
            await check(normal, system_error)
            for pin in INPUTS:
                if pin in ENABLE:
                    continue
                values[pin] = 1 - background
                getattr(dut, pin).value = values[pin]
                await check(normal, system_error)
                values[pin] = background
                getattr(dut, pin).value = values[pin]
            await check(normal, system_error)

    # Even with all controls permitting operation, startup stays safe for three edges.
    await check(False)
    for _ in range(3):
        await tick(1)
        await check(False)
    if HEARTBEAT:
        # Static CarrierReady cannot qualify, even after the startup guard.
        await tick(HEARTBEAT['timeout_clks'] + 3)
        await check(False)
        hb_running = True
        await tick(qualify_cycles)
    else:
        await tick(1)
    await check(True)
    dut.reqsafestate.value = REQUEST_SAFE
    if HEARTBEAT:
        # Request assertion is asynchronous, even with the clock held still.
        await check(False)
    await tick()
    await patterns(False)
    dut.reqsafestate.value = 1 - REQUEST_SAFE
    if HEARTBEAT:
        await check(False)
        await tick(1)
        await check(False)
        await tick(1)
    else:
        await tick()
    await patterns(True)
    dut.reqsafestate.value = REQUEST_SAFE
    await tick()
    await patterns(False)
    dut.reqsafestate.value = 1 - REQUEST_SAFE
    await tick()
    await check(True)

    dut.pilot_in.value = 0
    await tick()
    await check(not REQUIRE_PILOT)
    dut.pilot_in.value = 1
    await tick()
    await check(True)
    if not HEARTBEAT:
        dut.carrierrdy.value = 1 - READY_LEVEL
        await tick()
        await check(not USE_READY)
        dut.carrierrdy.value = READY_LEVEL
        await tick()
    await check(True)
    for pin, required in ENABLE.items():
        values[pin] = 1 - required
        getattr(dut, pin).value = values[pin]
        await tick()
        await check(False)
        values[pin] = required
        getattr(dut, pin).value = required
        await tick()
        await check(True)

    if HEARTBEAT:
        # Loss is still fatal during a static safe request. Every output,
        # including RX, constants and Z routes, must become zero.
        dut.reqsafestate.value = REQUEST_SAFE
        hb_running = False
        await tick(HEARTBEAT['timeout_clks'] + 3)
        await patterns(False, system_error=True)
        hb_running = True
        await tick(qualify_cycles)
        for request in (1 - REQUEST_SAFE, REQUEST_SAFE, 1 - REQUEST_SAFE):
            dut.reqsafestate.value = request
            dut.pilot_in.value = 1 - int(dut.pilot_in.value)
            for pin in ENABLE:
                values[pin] ^= 1
                getattr(dut, pin).value = values[pin]
            await tick(qualify_cycles)
            await patterns(False, system_error=True)
'''
