-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 1.2
-- Tue Dec 10 17:57:55 2024

-- parameterized module component declaration
component test
    port (wb_clk_i: in  std_logic; i2c1_scl: inout  std_logic; 
        i2c1_sda: inout  std_logic; i2c1_irqo: out  std_logic);
end component;

-- parameterized module component instance
__ : test
    port map (wb_clk_i=>__, i2c1_scl=>__, i2c1_sda=>__, i2c1_irqo=>__);
