-- Generated by cpld_vhdl_generator; regenerate instead of editing.
library ieee;
use ieee.std_logic_1164.all;

entity tx30_stateful is
    port (
        pilot_in : in std_logic;
        reqsafestate : in std_logic;
        carrierrdy : in std_logic;
        slotok : out std_logic;
        reqoe : out std_logic;
        i2c_scl : in std_logic;
        i2c_sda : in std_logic;
        fpga_00 : in std_logic;
        fpga_01 : in std_logic;
        fpga_02 : in std_logic;
        fpga_03 : in std_logic;
        fpga_04 : in std_logic;
        fpga_05 : in std_logic;
        fpga_06 : in std_logic;
        fpga_07 : in std_logic;
        fpga_08 : in std_logic;
        fpga_09 : in std_logic;
        fpga_10 : in std_logic;
        fpga_11 : in std_logic;
        fpga_12 : in std_logic;
        fpga_13 : in std_logic;
        fpga_14 : in std_logic;
        fpga_15 : in std_logic;
        fpga_16 : in std_logic;
        fpga_17 : in std_logic;
        fpga_18 : in std_logic;
        fpga_19 : in std_logic;
        fpga_20 : in std_logic;
        fpga_21 : in std_logic;
        fpga_22 : in std_logic;
        fpga_23 : in std_logic;
        fpga_24 : in std_logic;
        fpga_25 : in std_logic;
        fpga_26 : in std_logic;
        fpga_27 : in std_logic;
        fpga_28 : in std_logic;
        fpga_29 : in std_logic;
        d_00 : out std_logic;
        d_01 : out std_logic;
        d_02 : out std_logic;
        d_03 : out std_logic;
        d_04 : out std_logic;
        d_05 : out std_logic;
        d_06 : out std_logic;
        d_07 : out std_logic;
        d_08 : out std_logic;
        d_09 : out std_logic;
        d_10 : out std_logic;
        d_11 : out std_logic;
        d_12 : out std_logic;
        d_13 : out std_logic;
        d_14 : out std_logic;
        d_15 : out std_logic;
        d_16 : out std_logic;
        d_17 : out std_logic;
        d_18 : out std_logic;
        d_19 : out std_logic;
        d_20 : out std_logic;
        d_21 : out std_logic;
        d_22 : out std_logic;
        d_23 : out std_logic;
        d_24 : out std_logic;
        d_25 : out std_logic;
        d_26 : out std_logic;
        d_27 : out std_logic;
        d_28 : out std_logic;
        d_29 : out std_logic
    );
end entity;

architecture rtl of tx30_stateful is
    signal cvg_normal, cvg_error, cvg_card_enable : std_logic;
    signal cvg_clk : std_logic;
    signal cvg_reset : std_logic := '1';
    signal cvg_startup : natural range 0 to 3 := 0;
    component OSCH
        generic (NOM_FREQ : string := "2.08");
        port (STDBY : in std_logic; OSC, SEDSTDBY : out std_logic);
    end component;
begin
    oscillator: OSCH generic map (NOM_FREQ => "2.08")
        port map (STDBY => '0', OSC => cvg_clk, SEDSTDBY => open);
    process(cvg_clk)
    begin
        if rising_edge(cvg_clk) then
            if cvg_startup < 3 then
                cvg_startup <= cvg_startup + 1;
                cvg_reset <= '1';
            else
                cvg_reset <= '0';
            end if;
        end if;
    end process;
    cvg_card_enable <= '1';
    controller: entity work.s3c_logic
        port map (
            clk => cvg_clk,
            reset => cvg_reset,
            pilot_in => pilot_in,
            reqsafestate => reqsafestate,
            carrierrdy => carrierrdy,
            slotok => slotok,
            reqoe => reqoe,
            card_enable => cvg_card_enable,
            state_normal => cvg_normal,
            state_safe => open,
            state_error => cvg_error
        );
    d_00 <= fpga_00 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_01 <= fpga_01 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_02 <= fpga_02 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_03 <= fpga_03 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_04 <= fpga_04 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_05 <= fpga_05 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_06 <= fpga_06 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_07 <= fpga_07 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_08 <= fpga_08 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_09 <= fpga_09 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_10 <= fpga_10 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_11 <= fpga_11 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_12 <= fpga_12 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_13 <= fpga_13 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_14 <= fpga_14 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_15 <= fpga_15 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_16 <= fpga_16 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_17 <= fpga_17 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_18 <= fpga_18 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_19 <= fpga_19 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_20 <= fpga_20 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_21 <= fpga_21 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_22 <= fpga_22 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_23 <= fpga_23 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_24 <= fpga_24 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_25 <= fpga_25 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_26 <= fpga_26 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_27 <= fpga_27 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_28 <= fpga_28 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
    d_29 <= fpga_29 when cvg_normal = '1' else '0' when cvg_error = '1' else '0';
end architecture;
